apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: hello-fun
build:
  artifacts:
  - image: hello-fun
    custom:
      buildCommand: |-
        ./mvnw spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE
        if [ $PUSH_IMAGE ]; then
          docker push $IMAGE
        fi
      dependencies:
        paths:
          - src
          - pom.xml
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes/service.yaml
    - kubernetes/deployment.yaml
portForward:
  - resourceType: service
    resourceName: hello-fun
    port: 80
    localPort: 8080

profiles:
- name: local
  build:
    local:
      push: false
- name: native
  build:
    artifacts:
    - image: hello-fun
      custom:
        buildCommand: |-
          ./mvnw spring-boot:build-image -Pnative-buildpack -DskipTests -Dspring-boot.build-image.imageName=$IMAGE
          if [ $PUSH_IMAGE ]; then
            docker push $IMAGE
          fi
        dependencies:
          paths:
            - src
            - pom.xml
